[build]
warnings = "deny"

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "link-arg=/STACK:8388608", "-C", "target-feature=+crt-static"]

[target.aarch64-pc-windows-msvc]
rustflags = ["-C", "link-arg=/STACK:8388608", "-C", "target-feature=+crt-static", "-C", "link-arg=/arm64hazardfree"]

[env]
V8_FROM_SOURCE = { value = "1", force = true }
GN_ARGS = { value = "icu_use_data_file=false icu_copy_icudata_to_root_build_dir=false v8_depend_on_icu_data_file=false", force = true }
