export const NOTIFICATION_QUEUE_CAPACITY = 8;
export const TRANSIENT_NOTIFICATION_DEFAULT_DURATION_SECONDS = 8;
export const TRANSIENT_NOTIFICATION_MAXIMUM_DURATION_SECONDS = 30;
export const TRANSIENT_NOTIFICATION_MINIMUM_DURATION_SECONDS = 3;
